### ISSUE TITLE
GAME TITLE: Harvest December: Reharvested!

### ISSUE THREAD

**Issue by takoyaki99** [SilverCrow2323/Renpy-Vita-Portings#4]
# GAME INFO
- Game name: Harvest December: Reharvested
- Link:https://github.com/takoyaki99/Harvest-December-Reharvested-Portable and https://natirivers.itch.io/harvest-december-remake

# EVENTUAL EXTRA NOTES
- Info: I have the game files from Autumn (the person in charge of this) but have hit a few snags in the process of porting. If you could email me at takoyaki@kalli.st and we could work things out from there I would very much appreciate it!!

# SCREENSHOTS
![](https://img.itch.zone/aW1hZ2UvNjExOTc1LzY0MjQzMTMucG5n/original/pDvb1u.png)

Thank you very much!!

**Comment by SilverCrow2323** [comment]
I'v mailed you!

**Comment by SilverCrow2323** [comment]
Mate did you get my emails?
I've sent you a DL link

**Comment by takoyaki99** [comment]
Sorry! It seems like mine haven’t been sending? Either way I’ll download today and test. Thank you!!

**Comment by SilverCrow2323** [comment]
Could you send me any other game files you may have in addition to those obtained from the link you sent me? 
Ty;)
